version: 2.1

defaults: &defaults
  working_directory: ~/project/app
  docker:
    - image: cypress/browsers:chrome69
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ~/.npm
            - ~/.cache
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Unit test
          command: npm run test:unit
      - run:
          name: e2e test
          command: npm run test:e2e -- --headless --browser chrome
      - run:
          name: build
          command: npm run build
      - run:
          name: build-with-tracking
          command: npm run build-with-tracking
