name: RSK Explorer testnet build and deploy

on:
  push:
    branches: [develop]

# Declare default permissions as read only.
permissions: read-all

jobs:
  testnet_build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node 16
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a #v4.2.0
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build-with-tracking:testnet

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 #v4.1.0
        with:
          role-to-assume: ${{ secrets.TESTNET_ROLE_ARN }}
          aws-region: ${{ secrets.TESTNET_AWS_REGION }}

      - name: Deploy site to S3
        run: |
          aws s3 sync --sse aws:kms --sse-kms-key-id ${{ secrets.TESTNET_KMS_KEY_ID }} --delete --only-show-errors --exclude .gitkeep dist/ ${{ secrets.TESTNET_S3_BUCKET }}
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.TESTNET_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
